# yazi.toml

[manager]
show_hidden = true

ratio = [1, 1, 3]

sort_by = "mtime"
sort_reverse = true     # Enables descending order


sort_dir_first = true

linemode = "size_and_mtime"

show_symlink = true

[opener]
edit = [
	{ run = 'nvim "$@"', desc = "Edit with Neovim", block = true, for = "unix" },
	{ run = 'code %*',    orphan = true, desc = "code",           for = "windows" },
	{ run = 'code -w %*', block = true,  desc = "code (block)",   for = "windows" },
]